### ISSUE TITLE
shall we automatically create `dependabot.yml`

### ISSUE THREAD

**Issue by kjappelbaum** [cheminfo/generator-cheminfo#29]
I use 

```
version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "04:00"
  open-pull-requests-limit: 10
  commit-message:
    prefix: 'chore'
```

and would be happy to make a PR that automatically copies this to `.github`.

I'm asking since you do no longer copy the `.yml` for the GitHub actions but rather suggest to use the UI.
